### PR TITLE
decode: harden Part 15 block decoder

### PR DESCRIPTION
**Pull request by boxerab**

### CODE REVIEW

**Review by osamu620 — CHANGES_REQUESTED** [review]
I would like to have your comments on this as a commit message. Could you kindly modify this commit with explanatory comments?

**Comment by Jamaika1** [comment]
main_dec_64bec7f.exe -i image_21447_24bit-grok_9ae0d10.j2k -o xxx3a.raw -num_threads 1
Tile num x = 1, y = 1
ERROR: number of placeholder passes is too large.
elapsed time 1049.895       [ms]
throughput 6.958279 [Msamples/s]
throughput 0.143714 [usec/sample]

**Comment by osamu620** [comment]
> main_dec_64bec7f.exe -i image_21447_24bit-grok_9ae0d10.j2k -o xxx3a.raw -num_threads 1
> Tile num x = 1, y = 1
> ERROR: number of placeholder passes is too large.
I doubt the input codestream is JPEG 2000 Part 1 compliant or transcoded from the one. Placeholder passes cannot be produced within HT only coding pipeline.

> Why are there three files? Y, U, V
When you specify the output with .raw extension, color components are separately written.

**Comment by boxerab** [comment]
> I would like to have your comments on this as a commit message. Could you kindly modify this commit with explanatory comments?

good idea - I have added details in the commit message.

**Review by osamu620 — APPROVED** [review]

**Comment by osamu620** [comment]
@boxerab 
Given the commits, I have reread the 15444-15 specification.  Especially, the checking conditions for suffix length is useful to keep the codec compliant with the standard. Thanks for this hardening!

**Pull request merged**
