### PR TITLE
hwy: remove unnecessary lines from CMakeLists.txt

### PR DESCRIPTION
**Pull request by boxerab**
EMSCRIPTEN support is breaking compile on ARM RockPI.

### CODE REVIEW

**Comment by osamu620** [comment]
@boxerab 
EMSCRIPTEN is generally for WASM environment, am I right?

**Comment by boxerab** [comment]
> @boxerab
> EMSCRIPTEN is generally for WASM environment, am I right?

yes, that's right. It would be interesting to look into browser support in the future.

**Comment by aous72** [comment]
Just a thought.

Sandflow has a [javascript wrapper](https://www.npmjs.com/package/openht) for OpenJPH. It might be useful to use the same javascript API.  So, the back-end library can be easily replaced.

**Comment by boxerab** [comment]
> Sandflow has a [javascript wrapper](https://www.npmjs.com/package/openht) for OpenJPH. It might be useful to use the same javascript API. So, the back-end library can be easily replaced.

Sounds like a great idea.

**Pull request merged**
