### PR TITLE
block coding: use thread pool to improve performance

### PR DESCRIPTION
**Pull request by boxerab**
This patch allows block encoder and decoder to run in a thread pool, significantly speeding up the encoder and decoder.

### CODE REVIEW

**Comment by osamu620** [comment]
Looks good to me. I have confirmed this PR improves significantly the performance of the codec!

**Comment by osamu620** [comment]
@boxerab 
I would like to add your name as a contributor to this project. I wonder why your name is still missing. If you don't mind, please confirm your email address in the development environment is the same as the one registered to GitHub?

**Comment by boxerab** [comment]
> ... If you don't mind, please confirm your email address in the development environment is the same as the one registered to GitHub?

Thanks! Yes, that email works.

**Comment by osamu620** [comment]
I would like to record your contribution. Could you kindly check the lists on:
https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-graphs-on-your-profile/why-are-my-contributions-not-showing-up-on-my-profile

Best,
Osamu

**Comment by boxerab** [comment]
right, you can use this email

boxerab at protonmail dot com

**Comment by osamu620** [comment]
I found it is much easier to add the new email address to your GitHub account.
https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-email-preferences/adding-an-email-address-to-your-github-account

Otherwise, I think modifying the last 4 commits by yourself is the second way.

Changing the git log by me will destroy the right history to be recorded...

**Comment by boxerab** [comment]
good idea - I have added that email.

**Comment by osamu620** [comment]
Thanks:) If your contribution won't be reflected automatically, I suggest that you should run `clang-format` with `.clang-format` on the top of the repo and commit and push the formatted code.

**Pull request merged**
